version: "3"

services:
    frontend:
        build: ./client
        restart: always
        ports:
            - "3000:3000"
        volumes:
            - /app/node_modules
            - ./client:/app
    backend:
        build: ./server
        restart: always
        ports:
            - "5000:5000"
        depends_on:
            - postgres
        volumes:
            - /app/node_modules
            - ./server:/app
    postgres:
        image: postgres:alpine
        restart: always
        ports:
            - "5432:5432"
        environment:
            POSTGRES_PASSWORD: "1234"
            POSTGRES_USER: postgres
            POSTGRES_DB: apartment_test
        volumes:
            - postgres_data:/var/lib/postgres_data
            # - ./server/db/apartments_db.sql:

volumes:
    postgres_data:
        driver: local
