version: "3"

services:
    frontend:
        build: ./client
        restart: always
        ports:
            - "3000:3000"
        volumes:
            - /app/node_modules
            - ./client:/app
    backend:
        build: ./server
        restart: always
        ports:
            - "5000:5000"
        depends_on:
            - postgres
        environment:
            DATABASE_HOST: postgres
            DATABASE_PORT: "5432"
            DATABASE_USERNAME: postgres
            DATABASE_PASSWORD: "1234"
            DATABASE_BASENAME: apartment_test
        volumes:
            - /app/node_modules
            - ./server:/app
    postgres:
        image: "postgres:alpine"
        restart: always
        ports:
            - "5432:5432"
        environment:
            POSTGRES_PASSWORD: "1234"
            POSTGRES_USER: postgres
            POSTGRES_DB: apartment_test
        volumes:
            - ./server/postgres/dumb:/tmp/dumb
            - ./server/postgres/script:/docker-entrypoint-initdb.d
            - postgres_data:/var/lib/postgres_data

volumes:
    postgres_data:
        driver: local
